<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d1e567d0e8b622e6162666b
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbdocente_dbManager.php';
	
/*
 * SCHEMA DB Profesor
 * 
	{
		apellidos: {
			type: 'String'
		},
		cedula: {
			type: 'String'
		},
		nombres: {
			type: 'String'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/profesor',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'apellidos'	=> isset($body->apellidos)?$body->apellidos:'',
		'cedula'	=> isset($body->cedula)?$body->cedula:'',
		'nombres'	=> isset($body->nombres)?$body->nombres:'',
			);

	$obj = makeQuery("INSERT INTO profesor (_id, apellidos, cedula, nombres )  VALUES ( null, :apellidos, :cedula, :nombres   )", $params, false);

	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/profesor/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM profesor WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/profesor/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM profesor WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/profesor',	function () use ($app){
	makeQuery("SELECT * FROM profesor");
});


//CRUD - EDIT

$app->post('/profesor/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'apellidos'	    => isset($body->apellidos)?$body->apellidos:'',
		'cedula'	    => isset($body->cedula)?$body->cedula:'',
		'nombres'	    => isset($body->nombres)?$body->nombres:''	);

	$obj = makeQuery("UPDATE profesor SET  apellidos = :apellidos,  cedula = :cedula,  nombres = :nombres   WHERE _id = :id LIMIT 1", $params, false);

	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>